# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c026ccdb30c84971331b09a1f44286ba12eb6afa8ea224a16f7df7afff88702121fe183277a53e02920cdad6573c1d6238a499407edae4aae57ed8323676e4b7

test:
  secret_key_base: 86457725926e1c8c0e974dd66812a3aaef06f30b0c9bfd5852a82e4940eafc416bb2efced3a84b34346e9ffea8d8e264e2116d3cfa04300b064a91713794eae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
